[package]
description = "Support for rust-i18n crate."
edition = "2021"
license = "MIT"
name = "rust-i18n-support"
readme = "../../README.md"
repository = "https://github.com/longbridgeapp/rust-i18n"
version = "1.0.0"

[dependencies]
glob = "0.3"
once_cell = "1.10.0"
proc-macro2 = "1.0"
serde = "1"
serde_json = "1"
serde_yaml = "0.8"
thiserror = "1"
postcard = { version = "1", features = ["alloc"] }
fs-err = "2.9"
