[package]
description = "Extractor for rust-i18n crate."
edition = "2021"
license = "MIT"
name = "rust-i18n-extract"
readme = "../../README.md"
repository = "https://github.com/longbridgeapp/rust-i18n"
version = "0.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
ignore = "0.4"
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1"
regex = "1"
rust-i18n-support = { path = "../support", version = ">= 0.3" }
serde = "1"
serde_json = "1"
serde_yaml = "0.8"
syn = { version = "1", features = ["full"] }
fs-err = "2.9"
